import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { RadialBarChart, RadialBar, ResponsiveContainer, PolarAngleAxis } from "recharts";
import DashboardLayout from "../components/layout/DashboardLayout";
import api from "../utils/api";
import { RiDownloadLine, RiShareLine, RiCheckLine, RiAlertLine, RiHeartPulseLine } from "react-icons/ri";

const RISK_CONFIG = {
  Low: { color: "#00f5a0", glow: "rgba(0,245,160,0.3)", label: "Low Risk", desc: "Your stroke risk is well-managed. Keep up the great lifestyle habits." },
  Medium: { color: "#f5a623", glow: "rgba(245,166,35,0.3)", label: "Medium Risk", desc: "Some risk factors detected. Consult your doctor and make lifestyle adjustments." },
  High: { color: "#f53d3d", glow: "rgba(245,61,61,0.4)", label: "High Risk", desc: "Elevated stroke risk detected. Please consult a physician immediately." },
};

function RiskGauge({ score, color, glow }) {
  const data = [{ value: score, fill: color }];
  return (
    <div className="relative w-64 h-64 mx-auto">
      <ResponsiveContainer width="100%" height="100%">
        <RadialBarChart innerRadius="70%" outerRadius="90%" data={data} startAngle={225} endAngle={-45}>
          <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={0} tick={false} />
          <RadialBar dataKey="value" cornerRadius={10} background={{ fill: "rgba(255,255,255,0.04)" }} />
        </RadialBarChart>
      </ResponsiveContainer>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.p
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.5, type: "spring" }}
          className="font-display font-bold text-5xl"
          style={{ color }}
        >
          {score}%
        </motion.p>
        <p className="text-xs text-[var(--text-muted)] font-mono mt-1">risk score</p>
      </div>
      {/* Glow */}
      <div className="absolute inset-0 rounded-full pointer-events-none" style={{ boxShadow: `0 0 60px ${glow}`, borderRadius: "50%" }} />
    </div>
  );
}

export default function ResultsPage() {
  const { id } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    api.get(`/assessment/${id}/report`)
      .then(({ data }) => setReport(data.report))
      .finally(() => setLoading(false));
  }, [id]);

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!report) return;
    const content = `
NeuroCare AI — Stroke Risk Report
===================================
Patient ID: ${report.patient_id}
Date: ${new Date(report.created_at).toLocaleString()}

RISK RESULT
-----------
Risk Level: ${report.risk_level}
Risk Score: ${report.risk_score}%
AI Confidence: ${report.confidence}%

HEALTH INPUTS
-------------
Age: ${report.age}
BMI: ${report.bmi}
Avg Glucose Level: ${report.avg_glucose_level} mg/dL
Hypertension: ${report.hypertension ? "Yes" : "No"}
Heart Disease: ${report.heart_disease ? "Yes" : "No"}
Smoking Status: ${report.smoking_status}
Work Type: ${report.work_type}
Residence: ${report.residence_type}

RECOMMENDATIONS
---------------
${report.recommendations?.map((r, i) => `${i + 1}. ${r}`).join("\n")}

---
Generated by NeuroCare AI — For medical review only.
    `.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `neurocare-report-${id}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return (
    <DashboardLayout>
      <div className="flex items-center justify-center min-h-96">
        <div className="neural-loader" />
      </div>
    </DashboardLayout>
  );

  if (!report) return (
    <DashboardLayout>
      <div className="text-center py-20 text-[var(--text-muted)]">Report not found.</div>
    </DashboardLayout>
  );

  const cfg = RISK_CONFIG[report.risk_level] || RISK_CONFIG.Low;

  return (
    <DashboardLayout>
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="font-display font-bold text-3xl text-white">Assessment Results</h1>
            <p className="text-[var(--text-muted)] text-sm font-mono mt-1">{new Date(report.created_at).toLocaleString()}</p>
          </div>
          <div className="flex gap-3">
            <button onClick={handleShare} className="btn-ghost py-2.5 px-4 text-sm flex items-center gap-2">
              {copied ? <><RiCheckLine /> Copied!</> : <><RiShareLine /> Share</>}
            </button>
            <button onClick={handleDownload} className="btn-ghost py-2.5 px-4 text-sm flex items-center gap-2">
              <RiDownloadLine /> Download
            </button>
          </div>
        </div>

        {/* Main risk card */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass rounded-3xl border p-8 mb-6 text-center"
          style={{ borderColor: `${cfg.color}40`, background: `${cfg.color}05` }}
        >
          <motion.div initial={{ scale: 0.8 }} animate={{ scale: 1 }} transition={{ delay: 0.2, type: "spring" }}>
            <RiskGauge score={report.risk_score} color={cfg.color} glow={cfg.glow} />
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
            <div className="inline-flex items-center gap-2 px-5 py-2 rounded-full mt-6 mb-4 font-display font-semibold text-lg"
              style={{ background: `${cfg.color}15`, color: cfg.color, border: `1px solid ${cfg.color}40` }}>
              <RiAlertLine />
              {cfg.label}
            </div>
            <p className="text-[var(--text-secondary)] max-w-md mx-auto text-sm leading-relaxed">{cfg.desc}</p>

            <div className="flex items-center justify-center gap-8 mt-6">
              <div className="text-center">
                <p className="font-mono font-bold text-xl text-white">{report.confidence}%</p>
                <p className="text-xs text-[var(--text-muted)]">AI Confidence</p>
              </div>
              <div className="w-px h-8 bg-[var(--neural-border)]" />
              <div className="text-center">
                <p className="font-mono font-bold text-xl text-white">{report.age}y</p>
                <p className="text-xs text-[var(--text-muted)]">Age</p>
              </div>
              <div className="w-px h-8 bg-[var(--neural-border)]" />
              <div className="text-center">
                <p className="font-mono font-bold text-xl text-white">{report.bmi}</p>
                <p className="text-xs text-[var(--text-muted)]">BMI</p>
              </div>
            </div>
          </motion.div>
        </motion.div>

        {/* Health inputs summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
          className="glass rounded-2xl border border-[var(--neural-border)] p-6 mb-6"
        >
          <h3 className="font-display font-semibold text-white mb-4 flex items-center gap-2">
            <RiHeartPulseLine className="text-[var(--cyber-primary)]" /> Health Summary
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {[
              ["Glucose", `${report.avg_glucose_level} mg/dL`],
              ["Hypertension", report.hypertension ? "Yes" : "No"],
              ["Heart Disease", report.heart_disease ? "Yes" : "No"],
              ["Smoking", report.smoking_status],
              ["Work Type", report.work_type],
              ["Residence", report.residence_type],
            ].map(([k, v]) => (
              <div key={k} className="p-3 rounded-xl" style={{ background: "rgba(255,255,255,0.02)" }}>
                <p className="text-xs text-[var(--text-muted)]">{k}</p>
                <p className="text-sm font-display font-medium text-white mt-1">{v}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Recommendations */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}
          className="glass rounded-2xl border border-[var(--neural-border)] p-6 mb-6"
        >
          <h3 className="font-display font-semibold text-white mb-5">AI Recommendations</h3>
          <div className="space-y-3">
            {report.recommendations?.map((rec, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.5 + i * 0.07 }}
                className="flex items-start gap-3 p-3 rounded-xl"
                style={{ background: "rgba(0,212,245,0.04)", border: "1px solid rgba(0,212,245,0.08)" }}
              >
                <div className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 text-xs font-bold" style={{ background: cfg.color, color: "#040d1a" }}>
                  {i + 1}
                </div>
                <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{rec}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        <div className="flex gap-4">
          <Link to="/patient/assessment" className="btn-cyber flex-1 py-3 text-center text-sm">
            Run New Assessment
          </Link>
          <Link to="/patient/history" className="btn-ghost flex-1 py-3 text-center text-sm">
            View History
          </Link>
        </div>
      </div>
    </DashboardLayout>
  );
}
